funny=47
    echo -e "                                                              \033[1;93m+===================================+"
    echo -e "                                                              |                                   |"
    if [[ $funny == 47 ]]; then  echo -e "                                                              |     [Skid Software]     |"; fi; else echo -e "                                                              |     [Shim Building Menu Beta]     |"
    echo -e "                                                              |                                   |"
    echo -e "                                                              |                                   |"
    echo -e "                                                              |                                   |"
    echo -e "                                                              |                                   |"
    echo -e "                                                              |       {Made By Wave Demure}       |"
    echo -e "                                                              |                                   |"
    echo -e "                                                              +===================================+"
